/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesTemplatesWhatsappRouteImport } from './routes/modules.templates-whatsapp'
import { Route as ModulesTemplatesSmsRouteImport } from './routes/modules.templates-sms'
import { Route as ModulesTemplatesEmailRouteImport } from './routes/modules.templates-email'
import { Route as ModulesIntegrationsWhatsappRouteImport } from './routes/modules.integrations-whatsapp'
import { Route as ModulesEventsRouteImport } from './routes/modules.events'
import { Route as ModulesModuleRouteImport } from './routes/modules.$module'
import { Route as ModulesEventsIndexRouteImport } from './routes/modules.events.index'
import { Route as ModulesEventsScanRouteImport } from './routes/modules.events.scan'
import { Route as ModulesEventsRegistrantsRouteImport } from './routes/modules.events.registrants'
import { Route as ModulesEventsQrRouteImport } from './routes/modules.events.qr'
import { Route as ModulesEventsCreateRouteImport } from './routes/modules.events.create'
import { Route as ModulesEventsBulkQrRouteImport } from './routes/modules.events.bulk-qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesTemplatesWhatsappRoute =
  ModulesTemplatesWhatsappRouteImport.update({
    id: '/modules/templates-whatsapp',
    path: '/modules/templates-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModulesTemplatesSmsRoute = ModulesTemplatesSmsRouteImport.update({
  id: '/modules/templates-sms',
  path: '/modules/templates-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesTemplatesEmailRoute = ModulesTemplatesEmailRouteImport.update({
  id: '/modules/templates-email',
  path: '/modules/templates-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIntegrationsWhatsappRoute =
  ModulesIntegrationsWhatsappRouteImport.update({
    id: '/modules/integrations-whatsapp',
    path: '/modules/integrations-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModulesEventsRoute = ModulesEventsRouteImport.update({
  id: '/modules/events',
  path: '/modules/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleRoute = ModulesModuleRouteImport.update({
  id: '/modules/$module',
  path: '/modules/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesEventsIndexRoute = ModulesEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesEventsRoute,
} as any)
const ModulesEventsScanRoute = ModulesEventsScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => ModulesEventsRoute,
} as any)
const ModulesEventsRegistrantsRoute =
  ModulesEventsRegistrantsRouteImport.update({
    id: '/registrants',
    path: '/registrants',
    getParentRoute: () => ModulesEventsRoute,
  } as any)
const ModulesEventsQrRoute = ModulesEventsQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => ModulesEventsRoute,
} as any)
const ModulesEventsCreateRoute = ModulesEventsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ModulesEventsRoute,
} as any)
const ModulesEventsBulkQrRoute = ModulesEventsBulkQrRouteImport.update({
  id: '/bulk-qr',
  path: '/bulk-qr',
  getParentRoute: () => ModulesEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/events': typeof ModulesEventsRouteWithChildren
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
  '/modules/templates-email': typeof ModulesTemplatesEmailRoute
  '/modules/templates-sms': typeof ModulesTemplatesSmsRoute
  '/modules/templates-whatsapp': typeof ModulesTemplatesWhatsappRoute
  '/modules/events/bulk-qr': typeof ModulesEventsBulkQrRoute
  '/modules/events/create': typeof ModulesEventsCreateRoute
  '/modules/events/qr': typeof ModulesEventsQrRoute
  '/modules/events/registrants': typeof ModulesEventsRegistrantsRoute
  '/modules/events/scan': typeof ModulesEventsScanRoute
  '/modules/events/': typeof ModulesEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
  '/modules/templates-email': typeof ModulesTemplatesEmailRoute
  '/modules/templates-sms': typeof ModulesTemplatesSmsRoute
  '/modules/templates-whatsapp': typeof ModulesTemplatesWhatsappRoute
  '/modules/events/bulk-qr': typeof ModulesEventsBulkQrRoute
  '/modules/events/create': typeof ModulesEventsCreateRoute
  '/modules/events/qr': typeof ModulesEventsQrRoute
  '/modules/events/registrants': typeof ModulesEventsRegistrantsRoute
  '/modules/events/scan': typeof ModulesEventsScanRoute
  '/modules/events': typeof ModulesEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modules/$module': typeof ModulesModuleRoute
  '/modules/events': typeof ModulesEventsRouteWithChildren
  '/modules/integrations-whatsapp': typeof ModulesIntegrationsWhatsappRoute
  '/modules/templates-email': typeof ModulesTemplatesEmailRoute
  '/modules/templates-sms': typeof ModulesTemplatesSmsRoute
  '/modules/templates-whatsapp': typeof ModulesTemplatesWhatsappRoute
  '/modules/events/bulk-qr': typeof ModulesEventsBulkQrRoute
  '/modules/events/create': typeof ModulesEventsCreateRoute
  '/modules/events/qr': typeof ModulesEventsQrRoute
  '/modules/events/registrants': typeof ModulesEventsRegistrantsRoute
  '/modules/events/scan': typeof ModulesEventsScanRoute
  '/modules/events/': typeof ModulesEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modules/$module'
    | '/modules/events'
    | '/modules/integrations-whatsapp'
    | '/modules/templates-email'
    | '/modules/templates-sms'
    | '/modules/templates-whatsapp'
    | '/modules/events/bulk-qr'
    | '/modules/events/create'
    | '/modules/events/qr'
    | '/modules/events/registrants'
    | '/modules/events/scan'
    | '/modules/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modules/$module'
    | '/modules/integrations-whatsapp'
    | '/modules/templates-email'
    | '/modules/templates-sms'
    | '/modules/templates-whatsapp'
    | '/modules/events/bulk-qr'
    | '/modules/events/create'
    | '/modules/events/qr'
    | '/modules/events/registrants'
    | '/modules/events/scan'
    | '/modules/events'
  id:
    | '__root__'
    | '/'
    | '/modules/$module'
    | '/modules/events'
    | '/modules/integrations-whatsapp'
    | '/modules/templates-email'
    | '/modules/templates-sms'
    | '/modules/templates-whatsapp'
    | '/modules/events/bulk-qr'
    | '/modules/events/create'
    | '/modules/events/qr'
    | '/modules/events/registrants'
    | '/modules/events/scan'
    | '/modules/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesModuleRoute: typeof ModulesModuleRoute
  ModulesEventsRoute: typeof ModulesEventsRouteWithChildren
  ModulesIntegrationsWhatsappRoute: typeof ModulesIntegrationsWhatsappRoute
  ModulesTemplatesEmailRoute: typeof ModulesTemplatesEmailRoute
  ModulesTemplatesSmsRoute: typeof ModulesTemplatesSmsRoute
  ModulesTemplatesWhatsappRoute: typeof ModulesTemplatesWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/templates-whatsapp': {
      id: '/modules/templates-whatsapp'
      path: '/modules/templates-whatsapp'
      fullPath: '/modules/templates-whatsapp'
      preLoaderRoute: typeof ModulesTemplatesWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/templates-sms': {
      id: '/modules/templates-sms'
      path: '/modules/templates-sms'
      fullPath: '/modules/templates-sms'
      preLoaderRoute: typeof ModulesTemplatesSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/templates-email': {
      id: '/modules/templates-email'
      path: '/modules/templates-email'
      fullPath: '/modules/templates-email'
      preLoaderRoute: typeof ModulesTemplatesEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/integrations-whatsapp': {
      id: '/modules/integrations-whatsapp'
      path: '/modules/integrations-whatsapp'
      fullPath: '/modules/integrations-whatsapp'
      preLoaderRoute: typeof ModulesIntegrationsWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/events': {
      id: '/modules/events'
      path: '/modules/events'
      fullPath: '/modules/events'
      preLoaderRoute: typeof ModulesEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$module': {
      id: '/modules/$module'
      path: '/modules/$module'
      fullPath: '/modules/$module'
      preLoaderRoute: typeof ModulesModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/events/': {
      id: '/modules/events/'
      path: '/'
      fullPath: '/modules/events/'
      preLoaderRoute: typeof ModulesEventsIndexRouteImport
      parentRoute: typeof ModulesEventsRoute
    }
    '/modules/events/scan': {
      id: '/modules/events/scan'
      path: '/scan'
      fullPath: '/modules/events/scan'
      preLoaderRoute: typeof ModulesEventsScanRouteImport
      parentRoute: typeof ModulesEventsRoute
    }
    '/modules/events/registrants': {
      id: '/modules/events/registrants'
      path: '/registrants'
      fullPath: '/modules/events/registrants'
      preLoaderRoute: typeof ModulesEventsRegistrantsRouteImport
      parentRoute: typeof ModulesEventsRoute
    }
    '/modules/events/qr': {
      id: '/modules/events/qr'
      path: '/qr'
      fullPath: '/modules/events/qr'
      preLoaderRoute: typeof ModulesEventsQrRouteImport
      parentRoute: typeof ModulesEventsRoute
    }
    '/modules/events/create': {
      id: '/modules/events/create'
      path: '/create'
      fullPath: '/modules/events/create'
      preLoaderRoute: typeof ModulesEventsCreateRouteImport
      parentRoute: typeof ModulesEventsRoute
    }
    '/modules/events/bulk-qr': {
      id: '/modules/events/bulk-qr'
      path: '/bulk-qr'
      fullPath: '/modules/events/bulk-qr'
      preLoaderRoute: typeof ModulesEventsBulkQrRouteImport
      parentRoute: typeof ModulesEventsRoute
    }
  }
}

interface ModulesEventsRouteChildren {
  ModulesEventsBulkQrRoute: typeof ModulesEventsBulkQrRoute
  ModulesEventsCreateRoute: typeof ModulesEventsCreateRoute
  ModulesEventsQrRoute: typeof ModulesEventsQrRoute
  ModulesEventsRegistrantsRoute: typeof ModulesEventsRegistrantsRoute
  ModulesEventsScanRoute: typeof ModulesEventsScanRoute
  ModulesEventsIndexRoute: typeof ModulesEventsIndexRoute
}

const ModulesEventsRouteChildren: ModulesEventsRouteChildren = {
  ModulesEventsBulkQrRoute: ModulesEventsBulkQrRoute,
  ModulesEventsCreateRoute: ModulesEventsCreateRoute,
  ModulesEventsQrRoute: ModulesEventsQrRoute,
  ModulesEventsRegistrantsRoute: ModulesEventsRegistrantsRoute,
  ModulesEventsScanRoute: ModulesEventsScanRoute,
  ModulesEventsIndexRoute: ModulesEventsIndexRoute,
}

const ModulesEventsRouteWithChildren = ModulesEventsRoute._addFileChildren(
  ModulesEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesModuleRoute: ModulesModuleRoute,
  ModulesEventsRoute: ModulesEventsRouteWithChildren,
  ModulesIntegrationsWhatsappRoute: ModulesIntegrationsWhatsappRoute,
  ModulesTemplatesEmailRoute: ModulesTemplatesEmailRoute,
  ModulesTemplatesSmsRoute: ModulesTemplatesSmsRoute,
  ModulesTemplatesWhatsappRoute: ModulesTemplatesWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
